name: Django CI

on:
  push:
    branches:
      - master  # This ensures it runs on the 'master' branch
  pull_request:
    branches:
      - master  # This ensures it runs for PRs on the 'master' branch

jobs:
  test:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner
    
    steps:
      - name: Check out the code
        uses: actions/checkout@v3  # Checkout the code from the repository

      - name: Set up Python
        uses: actions/setup-python@v4  # Set up Python environment
        with:
          python-version: 3.9  # Specify Python version to use

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip  # Upgrade pip to the latest version
          pip install -r requirements.txt  # Install dependencies from 'requirements.txt'
      - name: Run Tests
        run: |
          python manage.py test  # Run the Django tests using the manage.py file
