name: Run Django Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9  # Update to match your Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Set environment variables
      run: echo "DEBUG=true" >> $GITHUB_ENV

    - name: Set up database
      run: python manage.py migrate

    - name: Run Django test
      run: python manage.py test test.login-test.py --verbosity 3

    - name: Debugging on failure
      if: failure()
      run: |
        echo "Tests failed with exit code $?"
        ls -la
        cat manage.py
